* suspend and poweroff events
  the following is my ~/etc/systemd/logind.conf~
  #+BEGIN_SRC conf
    [Login]
    HandlePowerKey=suspend
    HandleSuspendKey=poweroff
    HandleLidSwitch=suspend
    HandleLidSwitchDocked=ignore
  #+END_SRC
  i have swapped the suspend and power keys because, on my laptop, ~poweroff~
  has its own key above the backspace (which i frequently hit on accident),
  whereas ~suspend~ is ~<fn>-<esc>~, which is easy to hit on purpose but hard
  to hit on accident.

  these are supposedly the default settings for ~HandleLidSwitch~ and
  ~HandleLidSwitchDocked~, but until i set them, my laptop was not suspending
  when i closed the lid.
* lightdm no sound
  i created a file
  [[file:/usr/share/glib-2.0/schemas/50_unity-greeter.gschema.override][/usr/share/glib-2.0/schemas/50_unity-greeter.gschema.override]]
  with the following contents:
  #+BEGIN_SRC conf
    [com.canonical.unity-greeter]
    play-ready-sound = false
  #+END_SRC
  the available fields and defaults are in
  [[file:/usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml]]
* making arm64 chroot
  #+BEGIN_SRC sh
    sudo mkdir /arm64
    sudo debootstrap --arch=arm64 stable /arm64
  #+END_SRC
* building sbcl in chroot
  #+BEGIN_SRC sh
    sudo chroot /arm64 sh -c 'cd /opt/sbcl-src ; sh make.sh --arch=arm64 --prefix=/opt/sbcl64'
  #+END_SRC
  install it in the chroot with:
  #+BEGIN_SRC sh
    sudo chroot /arm64 sh -c 'cd /opt/sbcl-src ; sh install.sh'
  #+END_SRC
  install it globally the normal way:
  #+BEGIN_SRC sh
    sudo sh install.sh
  #+END_SRC
  make sure it's symlinked with
  #+BEGIN_SRC sh
    sudo ln -s /opt/sbcl64/bin/sbcl /usr/local/bin/sbcl64
  #+END_SRC
  additionally, symlink it as ~sbcl~ with:
  #+BEGIN_SRC sh
    sudo ln -s /usr/local/bin/sbcl64 /usr/local/bin/sbcl
  #+END_SRC
* building sbcl32
  #+BEGIN_SRC sh
    sh make.sh --arch=arm --prefix=/opt/sbcl32
  #+END_SRC
  make sure it's symlinked with
  #+BEGIN_SRC sh
    sudo ln -s /opt/sbcl32/bin/sbcl /usr/local/bin/sbcl32
  #+END_SRC
* font
  [[https://input.fontbureau.com/download/?customize&fontSelection=whole&a=0&g=0&i=serifs&l=serifs_round&zero=0&asterisk=0&braces=0&preset=default&line-height=1.2&accept=I+do&email=][download input]].
  #+BEGIN_SRC sh
    unzip Input_Font.zip
  #+END_SRC
  install:
  #+BEGIN_SRC sh
    for font in $(ls -d Input_Font/*/*/); do
        cp $font ~/.fonts/
    done
    fc-cache -v -f
  #+END_SRC
* disable wifi powersave
  to see the power save setting, do:
  #+BEGIN_SRC sh
    iw dev wlan0 get power_save
  #+END_SRC
** temporarily disable
   to disable it temporarily, do:
   #+BEGIN_SRC sh
    iw dev wlan0 set power_save off
   #+END_SRC
** permanently disable - networkmanager conf.d
   as root, delete
   [[file:/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf]] and replace it
   with [[file:/etc/NetworkManager/conf.d/default-wifi-powersave-off.conf]] with the
   contents:
   #+BEGIN_SRC conf
    [connection]
    wifi.powersave = 2
   #+END_SRC
** permanently disable - power.d
   #+BEGIN_SRC sh
     sudo touch /etc/pm/power.d/wireless
   #+END_SRC
* touchpad
  touchpad configuration goes in [[file:/etc/X11/xorg.conf.d/30-touchpad.conf]]. 

  all told, mine looks like:
  #+BEGIN_SRC conf
    Section "InputClass"
        Identifier "touchpad"
        Driver "libinput"
        MatchIsTouchpad "on"
        Option "Tapping" "off"
        Option "TransformationMatrix" "4.0 0.0 0.0 0.0 4.0 0.0 0.0 0.0 1.0"
    EndSection
  #+END_SRC

  the options i've added or changed are:
** disable tapping
   tapping with this touchpad makes typing hard. it's too sensitive.
   #+BEGIN_SRC conf
     Option "Tapping" "off"
   #+END_SRC
** raise mouse speed
   the transformation matrix is a 3x3 matrix. by default, it's an identity
   matrix. ~0, 0~ seems to be the x speed, and ~1, 1~ the y speed. i've ramped
   each of those up to 4x. note that, for reasons beyond my comprehension,
   these are divided by ~2, 2~, so setting that to ~4.0~ rather than ~1.0~
   would return the mouse speed to the default.

   #+BEGIN_SRC conf
     Option "TransformationMatrix" "4.0 0.0 0.0 0.0 4.0 0.0 0.0 0.0 1.0"
   #+END_SRC
* keyboard layout
  i have an iso pinebook, but i still want it configured in software to use the
  us keyboard layout. the manjaro installer doesn't offer that as an option, so
  i have to edit [[file:/etc/X11/xorg.conf.d/00-keyboard.conf]] to contain:
  #+BEGIN_SRC conf
            Option "XkbLayout" "us"
            Option "XkbModel" "pc105"
  #+END_SRC
  all told, the contents of that file are:
  #+BEGIN_SRC conf
    Section "InputClass"
            Identifier "system-keyboard"
            MatchIsKeyboard "on"
            Option "XkbLayout" "us"
            Option "XkbModel" "pc105"
            Option "XkbOptions" "terminate:ctrl_alt_bksp"
    EndSection
  #+END_SRC
* theme
** cursors
   i use the cursors from Chicago95. to install these, clone Chicago95, and
   copy the cursors into [[file:/usr/share/icons/]]:
   #+BEGIN_SRC sh
     hub clone grassmunk/Chicago95 ~/Chicago95
     sudo cp -r ~/Chicago95/Cursors/* /usr/share/icons/
   #+END_SRC
   then, make them the default by editing both
   [[file:/usr/share/icons/default/index.theme]] and [[file:~/.icons/default/index.theme]] to contain:
   #+BEGIN_SRC conf
     [Icon Theme]
     Inherits=Chicago95_Cursor_Black
   #+END_SRC
   and enable them in gtk by chainging [[file:~/.config/gtk-3.0/settings.ini]] to
   contain:
   #+BEGIN_SRC conf
     [Settings]
     gtk-cursor-theme-name=Chicago95_Cursor_Black
   #+END_SRC
   enable in LightDM by editing [[file:/etc/lightdm/lightdm-gtk-greeter.conf]] to
   contain:
   #+BEGIN_SRC conf
     [greeter]
     cursor-theme-name = Chicago95_Cursor_Black
   #+END_SRC
** lightdm background color
   edit [[file:/etc/lightdm/lightdm-gtk-greeter.conf]] to contain:
   #+BEGIN_SRC conf
     background = #282a36
   #+END_SRC
** colors
   in keeping with my love of dracula, i use the gtk theme
   [[https://github.com/EliverLara/Ant-Dracula]]. clone it:
   #+BEGIN_SRC sh
     hub clone EliverLara/Ant-Dracula ~/Ant-Dracula
   #+END_SRC
   then, install it:
   #+BEGIN_SRC sh
     sudo cp -r ~/Ant-Dracula /usr/share/themes/
   #+END_SRC
   set this as the lightdm theme by editing
   [[file:/etc/lightdm/lightdm-gtk-greeter.conf]] to contain:
   #+BEGIN_SRC conf
     theme-name = Ant-Dracula
   #+END_SRC
** icons
   my window manager doesn't have any icons, but i have lightdm configured to
   use the Chicago95 icons. install them:
   #+BEGIN_SRC sh
     sudo cp -r ~/Chicago95/Icons/* /usr/share/icons/
   #+END_SRC
   edit [[file:/etc/lightdm/lightdm-gtk-greeter.conf]] to contain:
   #+BEGIN_SRC conf
     icon-theme-name = Chicago95
   #+END_SRC
* zsh
  install zsh with
  #+BEGIN_SRC sh
    sudo pacman -Syu zsh
  #+END_SRC
  then, get oh-my-zsh with
  #+BEGIN_SRC sh
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  #+END_SRC
** theme
   next, get the dracula theme:
   #+BEGIN_SRC sh
     git clone https://github.com/dracula/zsh.git ~/zsh-theme-dracula
     ln -s ~/zsh-theme-dracula/dracula.zsh-theme ~/.oh-my-zsh/themes/dracula.zsh-theme
   #+END_SRC
   change [[file:~/.zshrc][.zshrc]] to include:
   #+BEGIN_SRC sh
     ZSH_THEME="dracula"
   #+END_SRC
** autocomplete
   clone the zsh-autosuggestions repo:
   #+BEGIN_SRC sh
     git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
   #+END_SRC
   and add it to your [[file:~/.zshrc][.zshrc]]:
   #+BEGIN_SRC sh
     plugins=(.. zsh-autosuggestions)
   #+END_SRC
